# Site
url: "https://www.melihkocaturk.com"
lang: tr
title: Melih Kocatürk
description: Emlak danışmanından ipuçları ve stratejiler, arsa yatırımı, konut alım-satımı ve emlak sektörü hakkında güvenilir bilgiler...
words_per_minute: 190

## Home
home: 
  info: Bu blog, gayrimenkul danışmanlığı alanında bilgi arayan bireyler için güvenilir, sade ve anlaşılır içerikler sunmak amacıyla hazırlanmıştır. Emlak sektörüne dair güncel bilgiler, yatırım ve işlem süreçleri hakkında rehberlik sağlayarak, okuyucuların daha bilinçli kararlar almasına katkı sağlamayı hedeflemektedir.
  get-in-touch: Gayrimenkul ile ilgili her türlü soru, öneri ya da iş birliği talebiniz için benimle iletişime geçebilirsiniz. Evinizi satmak, yeni bir yaşam alanı bulmak ya da yatırım fırsatlarını değerlendirmek istiyorsanız, doğru yerdesiniz.

# Contact
contact:
  gsm: +90 546 566 55 09
  phone: +90 212 397 11 00
  email: melih.kocaturk@kww.com.tr
  address: Keller Williams Fores, Halide Edip Adıvar Mh. Akar Cd. No:22/A Kat:3 Şişli/İstanbul

# Permalinks
permalink: /:title

# Pagination
paginate: 5
paginate_path: /sayfa:num/

# Social
social: 
  linkedin: https://www.linkedin.com/in/melihkocaturk/
  instagram: https://www.instagram.com/melih_kocaturk_
  youtube: https://www.youtube.com/@melihkocaturk

# Google Analytics
google_analytics: G-D81YCKRVTX

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
